// Texto bíblico que el usuario pegó en el chat (Traducción del Nuevo Mundo) para guardarlo en su
// "Mi Biblia". Sin las marcas de notas al pie (+ y *). Se guarda versículo por versículo.

export const JEREMIAS_38_39 = [
  ['Jeremías 38:1', 'Sefatías hijo de Matán, Guedalías hijo de Pasjur, Jucal hijo de Selemías y Pasjur hijo de Malkiya oyeron estas palabras que Jeremías le estaba diciendo a todo el pueblo:'],
  ['Jeremías 38:2', '“Esto es lo que dice Jehová: ‘El que se quede en esta ciudad morirá por la espada, el hambre y la peste. Pero el que se rinda ante los caldeos seguirá viviendo; su propia vida será su botín de guerra y él vivirá’.'],
  ['Jeremías 38:3', 'Esto es lo que dice Jehová: ‘Esta ciudad sin falta será entregada en manos del ejército del rey de Babilonia, y él la conquistará’”.'],
  ['Jeremías 38:4', 'Los príncipes le dijeron al rey: “Por favor, haz que maten a este hombre, porque con las cosas que dice está desmoralizando a los soldados que quedan en esta ciudad y a todo el pueblo. Porque este hombre no quiere la paz para este pueblo, sino la calamidad”.'],
  ['Jeremías 38:5', 'El rey Sedequías dijo: “Miren, ahí lo tienen, está en sus manos, porque el rey no puede hacer nada para detenerlos a ustedes”.'],
  ['Jeremías 38:6', 'Así que agarraron a Jeremías y lo arrojaron en la cisterna de Malkiya, el hijo del rey, en el Patio de la Guardia; lo bajaron con sogas. En la cisterna no había agua, solo fango, y Jeremías empezó a hundirse en el fango.'],
  ['Jeremías 38:7', 'Ébed-Mélec el etíope, un eunuco de la casa del rey, se enteró de que habían metido a Jeremías en la cisterna. El rey estaba sentado en la Puerta de Benjamín,'],
  ['Jeremías 38:8', 'así que Ébed-Mélec salió de la casa del rey y le dijo:'],
  ['Jeremías 38:9', '“¡Oh, mi señor el rey, lo que esos hombres le han hecho al profeta Jeremías es muy cruel! Lo han arrojado a la cisterna, y allí se va a morir de hambre, porque ya no queda pan en la ciudad”.'],
  ['Jeremías 38:10', 'Entonces el rey le ordenó a Ébed-Mélec el etíope: “Llévate de aquí a 30 hombres y saca al profeta Jeremías de la cisterna antes de que se muera”.'],
  ['Jeremías 38:11', 'Así que Ébed-Mélec se llevó a los hombres y fue a la casa del rey, a un lugar debajo de la cámara del tesoro, y se llevaron de allí algunos trapos viejos y pedazos de tela gastada, y se los bajaron con sogas a Jeremías en la cisterna.'],
  ['Jeremías 38:12', 'Entonces Ébed-Mélec el etíope le dijo a Jeremías: “Por favor, ponte los trapos y los pedazos de tela entre las axilas y las sogas”. Jeremías lo hizo,'],
  ['Jeremías 38:13', 'y ellos lo fueron subiendo con las sogas y lo sacaron de la cisterna. Y Jeremías se quedó en el Patio de la Guardia.'],
  ['Jeremías 38:14', 'El rey Sedequías mandó traer al profeta Jeremías a la tercera entrada, que está en la casa de Jehová, y el rey le dijo a Jeremías: “Tengo que preguntarte algo. No me ocultes nada”.'],
  ['Jeremías 38:15', 'Jeremías entonces le dijo a Sedequías: “Si te lo digo, seguro que me vas a matar. Y, si te doy un consejo, no me vas a escuchar”.'],
  ['Jeremías 38:16', 'Así que Sedequías le juró a Jeremías a escondidas: “Tan cierto como que vive Jehová, quien nos ha dado esta vida, yo no te voy a matar ni te voy a entregar a estos hombres que quieren quitarte la vida”.'],
  ['Jeremías 38:17', 'Jeremías entonces le dijo a Sedequías: “Esto es lo que dice Jehová, el Dios de los ejércitos, el Dios de Israel: ‘Si te rindes ante los príncipes del rey de Babilonia, tú seguirás con vida, esta ciudad no será quemada con fuego, y tú y los de tu casa no morirán.'],
  ['Jeremías 38:18', 'Pero, si no te rindes ante los príncipes del rey de Babilonia, entonces esta ciudad será entregada en manos de los caldeos, ellos la quemarán con fuego y tú no escaparás de sus manos’”.'],
  ['Jeremías 38:19', 'Entonces el rey Sedequías le dijo a Jeremías: “Les tengo miedo a los judíos que se han pasado al bando de los caldeos. Porque, si me entregan en sus manos, ellos tal vez me traten con crueldad”.'],
  ['Jeremías 38:20', 'Pero Jeremías dijo: “No serás entregado en sus manos. Por favor, obedece la voz de Jehová y haz lo que te estoy diciendo; así te irá bien y seguirás viviendo.'],
  ['Jeremías 38:21', 'Pero, si te niegas a rendirte, Jehová me ha revelado que pasará esto:'],
  ['Jeremías 38:22', '¡mira!, sacarán a todas las mujeres que quedan en la casa del rey de Judá y se las llevarán a los príncipes del rey de Babilonia, y ellas irán diciendo:\n‘Los hombres en los que confiabas te han engañado y te han vencido.\nHan hecho que tus pies se hundan en el fango.\nAhora se han dado la vuelta en retirada’.'],
  ['Jeremías 38:23', 'Y a todas tus esposas y tus hijos los entregarán a los caldeos. Y tú no podrás escapar de sus manos, sino que el rey de Babilonia te capturará, y por tu culpa quemarán con fuego esta ciudad”.'],
  ['Jeremías 38:24', 'Luego Sedequías le dijo a Jeremías: “No le digas nada de esto a nadie, para que no mueras.'],
  ['Jeremías 38:25', 'Y, si los príncipes se enteran de que hablé contigo y vienen a decirte ‘Por favor, cuéntanos lo que le dijiste al rey. No nos ocultes nada y no te mataremos. ¿Y qué te dijo el rey a ti?’,'],
  ['Jeremías 38:26', 'entonces tienes que responderles ‘Estaba pidiéndole al rey que no me enviara de vuelta a la casa de Jehonatán a morir allí’”.'],
  ['Jeremías 38:27', 'Tiempo después, todos los príncipes vinieron a ver a Jeremías y lo interrogaron. Él les dijo todo lo que el rey le había mandado decir. Así que ellos no le preguntaron nada más, porque ninguno había escuchado la conversación.'],
  ['Jeremías 38:28', 'Jeremías permaneció en el Patio de la Guardia hasta el día en que conquistaron Jerusalén; él todavía estaba allí cuando Jerusalén fue conquistada.'],

  ['Jeremías 39:1', 'En el noveno año del rey Sedequías de Judá, en el décimo mes, el rey Nabucodonosor de Babilonia vino con todo su ejército a Jerusalén y la cercaron.'],
  ['Jeremías 39:2', 'En el año 11 de Sedequías, en el cuarto mes, el día nueve del mes, atravesaron la muralla de la ciudad.'],
  ['Jeremías 39:3', 'Y todos los príncipes del rey de Babilonia entraron y se sentaron en la Puerta del Medio. Eran el samgar Nergal-Sarézer, el rabsarís Nebo-Sarsekim, el rabmag Nergal-Sarézer y todos los demás príncipes del rey de Babilonia.'],
  ['Jeremías 39:4', 'Cuando el rey Sedequías de Judá y todos los soldados los vieron, huyeron de la ciudad. Salieron de noche por el jardín del rey, por la puerta que había entre las dos murallas, y continuaron por el camino del Arabá.'],
  ['Jeremías 39:5', 'Pero el ejército de los caldeos los persiguió, y alcanzaron a Sedequías en las llanuras desérticas de Jericó. Lo capturaron y se lo llevaron al rey Nabucodonosor de Babilonia en Riblá, en la tierra de Hamat, y allí lo sentenció.'],
  ['Jeremías 39:6', 'El rey de Babilonia hizo que mataran a los hijos de Sedequías allí en Riblá, ante sus propios ojos. Y el rey de Babilonia también hizo que mataran a todos los nobles de Judá.'],
  ['Jeremías 39:7', 'Luego cegó a Sedequías y lo sujetó con grilletes de cobre para llevárselo a Babilonia.'],
  ['Jeremías 39:8', 'Entonces los caldeos quemaron la casa del rey y las casas del pueblo, y demolieron las murallas de Jerusalén.'],
  ['Jeremías 39:9', 'Nebuzaradán, el jefe de la guardia, se llevó al destierro en Babilonia al resto de la gente que quedaba en la ciudad, a los desertores que se habían pasado a su bando y a todos los que quedaban.'],
  ['Jeremías 39:10', 'Pero Nebuzaradán, el jefe de la guardia, dejó en la tierra de Judá a algunas de las personas más pobres, las que no tenían nada. Aquel día también les dio viñas y campos para que trabajaran.'],
  ['Jeremías 39:11', 'Ahora bien, el rey Nabucodonosor de Babilonia le dio a Nebuzaradán, el jefe de la guardia, estas órdenes acerca de Jeremías:'],
  ['Jeremías 39:12', '“Ve a buscarlo y cuida de él; no le hagas daño y dale todo lo que te pida”.'],
  ['Jeremías 39:13', 'Así que Nebuzaradán —el jefe de la guardia—, el rabsarís Nebusazbán, el rabmag Nergal-Sarézer y todos los hombres principales del rey de Babilonia mandaron'],
  ['Jeremías 39:14', 'sacar a Jeremías del Patio de la Guardia y se lo entregaron a Guedalías, hijo de Ahicam, hijo de Safán, para llevarlo a su casa. Así que Jeremías vivió entre el pueblo.'],
  ['Jeremías 39:15', 'Cuando Jeremías estuvo preso en el Patio de la Guardia, recibió estas palabras de Jehová:'],
  ['Jeremías 39:16', '“Ve y dile a Ébed-Mélec el etíope: ‘Esto es lo que dice Jehová de los ejércitos, el Dios de Israel: “Voy a cumplir mis palabras sobre esta ciudad, palabras de calamidad y no de cosas buenas, y ese día las verás cumplirse”’.'],
  ['Jeremías 39:17', '”‘Pero yo te rescataré ese día —afirma Jehová—, y no serás entregado en manos de los hombres que te dan miedo’.'],
  ['Jeremías 39:18', '”‘Porque sin falta te libraré, y no caerás a espada. Tu propia vida será tu botín de guerra, porque confiaste en mí’, afirma Jehová”.'],
]

// Daniel 2 completo, como el usuario lo pegó en el chat (3 de octubre de 2026).
export const DANIEL_2 = [
  ['Daniel 2:1', 'En el segundo año de su reinado, Nabucodonosor tuvo varios sueños, y él se inquietó tanto que no conseguía dormir.'],
  ['Daniel 2:2', 'Así que el rey mandó llamar a los sacerdotes-magos, los adivinos, los hechiceros y los caldeos para que le dijeran lo que había soñado. Entonces, ellos entraron y se presentaron ante el rey.'],
  ['Daniel 2:3', 'El rey les dijo: “He tenido un sueño, y estoy inquieto porque quiero saber lo que soñé”.'],
  ['Daniel 2:4', 'Los caldeos le respondieron al rey en arameo: “¡Oh, rey, vive eternamente! Cuéntales el sueño a tus siervos, y nosotros te diremos su interpretación”.'],
  ['Daniel 2:5', 'El rey les contestó a los caldeos: “Esta es mi decisión final: si no me revelan el sueño y su interpretación, haré que ustedes sean desmembrados y que sus casas se conviertan en letrinas públicas;'],
  ['Daniel 2:6', 'en cambio, si me revelan el sueño y su interpretación, les daré regalos, recompensas y grandes honores. Así pues, díganme el sueño y su interpretación”.'],
  ['Daniel 2:7', 'Por segunda vez, ellos le respondieron: “Que el rey les cuente el sueño a sus siervos, y nosotros le diremos su interpretación”.'],
  ['Daniel 2:8', 'El rey les respondió: “Me doy perfecta cuenta de que están tratando de ganar tiempo, porque ya saben cuál es mi decisión final.'],
  ['Daniel 2:9', 'Si no me revelan el sueño, hay un único castigo para todos ustedes. Pero ustedes se han puesto de acuerdo para contarme una mentira y engañarme esperando a que cambie la situación. De modo que revélenme el sueño y así sabré que pueden darme su interpretación”.'],
  ['Daniel 2:10', 'Los caldeos le contestaron al rey: “No hay ningún hombre en toda la tierra capaz de hacer lo que pide el rey. De hecho, ningún gran rey ni gobernador le ha pedido algo así a ningún sacerdote-mago ni adivino ni caldeo.'],
  ['Daniel 2:11', 'Lo que el rey pide es difícil y no existe nadie que pueda revelarle eso al rey salvo los dioses, que no residen entre los mortales”.'],
  ['Daniel 2:12', 'Al oír esto, el rey se puso terriblemente furioso y ordenó exterminar a todos los sabios de Babilonia.'],
  ['Daniel 2:13', 'Cuando se dio esta orden y estaban a punto de exterminar a los sabios, también fueron a buscar a Daniel y sus compañeros para matarlos.'],
  ['Daniel 2:14', 'Entonces Daniel se dirigió con discreción y prudencia a Arioc, que era el jefe de la guardia personal del rey y había salido a matar a los sabios de Babilonia.'],
  ['Daniel 2:15', 'Le preguntó a Arioc, el oficial del rey: “¿Por qué ha dado el rey una orden tan severa?”. Entonces Arioc le contó todo a Daniel.'],
  ['Daniel 2:16', 'Así que Daniel fue y le pidió al rey que le concediera tiempo para revelarle la interpretación.'],
  ['Daniel 2:17', 'Después Daniel se fue a su casa y les contó lo que pasaba a sus compañeros Hananías, Misael y Azarías.'],
  ['Daniel 2:18', 'Les pidió que le suplicaran misericordia al Dios del cielo en cuanto a ese secreto, para que ni Daniel ni sus compañeros fueran exterminados con los demás sabios de Babilonia.'],
  ['Daniel 2:19', 'Entonces, durante la noche, se le reveló el secreto a Daniel en una visión. De modo que Daniel alabó al Dios del cielo.'],
  ['Daniel 2:20', 'Daniel dijo: “Alabado sea el nombre de Dios por toda la eternidad, porque solo de él son la sabiduría y el poder.'],
  ['Daniel 2:21', 'Él cambia tiempos y épocas, quita reyes y pone reyes, da sabiduría a los sabios y conocimiento a los que tienen discernimiento.'],
  ['Daniel 2:22', 'Revela las cosas profundas y las cosas ocultas, sabe lo que está en la oscuridad, y la luz reside con él.'],
  ['Daniel 2:23', 'A ti te doy gracias y te alabo, oh, Dios de mis antepasados, porque me has dado sabiduría y poder. Y ahora me has revelado lo que te hemos pedido; nos has revelado lo que le preocupa al rey”.'],
  ['Daniel 2:24', 'Entonces Daniel fue adonde estaba Arioc, a quien el rey le había encargado que matara a los sabios de Babilonia, y le dijo: “No mates a ninguno de los sabios de Babilonia. Llévame ante el rey y yo le revelaré la interpretación”.'],
  ['Daniel 2:25', 'Rápidamente, Arioc llevó a Daniel ante el rey y le dijo: “He encontrado a un hombre entre los desterrados de Judá que puede revelarle la interpretación al rey”.'],
  ['Daniel 2:26', 'Entonces el rey le dijo a Daniel, a quien llamaban Beltsasar: “¿De veras puedes revelarme el sueño que vi y su interpretación?”.'],
  ['Daniel 2:27', 'Daniel le respondió al rey: “Ninguno de los sabios, adivinos, sacerdotes-magos ni astrólogos puede revelarle al rey el secreto que quiere saber.'],
  ['Daniel 2:28', 'Pero hay un Dios en los cielos que revela los secretos, y él le ha anunciado al rey Nabucodonosor lo que va a suceder en la parte final de los días. Estos son tu sueño y las visiones que tuviste en tu cabeza cuando estabas acostado en tu cama:'],
  ['Daniel 2:29', '”Oh, rey, cuando estabas acostado en tu cama, te pusiste a pensar en lo que sucedería en el futuro, y el que revela los secretos te ha anunciado lo que va a pasar.'],
  ['Daniel 2:30', 'Este secreto no se me ha revelado a mí porque tenga más sabiduría que cualquier otra persona. Más bien, se me reveló para que el rey supiera la interpretación y así tú conocieras los pensamientos de tu corazón.'],
  ['Daniel 2:31', '”Tú, oh, rey, estabas mirando y entonces viste una estatua enorme. Esa estatua, que era inmensa y extremadamente brillante, estaba de pie enfrente de ti y tenía un aspecto aterrador.'],
  ['Daniel 2:32', 'La cabeza de la estatua estaba hecha de oro fino; el pecho y los brazos eran de plata; el vientre y los muslos, de cobre;'],
  ['Daniel 2:33', 'sus piernas, de hierro, y sus pies eran en parte de hierro y en parte de barro.'],
  ['Daniel 2:34', 'Mientras mirabas, se cortó una piedra, aunque no con manos humanas. Y esta golpeó los pies de hierro y barro de la estatua y los hizo añicos.'],
  ['Daniel 2:35', 'Entonces el hierro, el barro, el cobre, la plata y el oro fueron hechos añicos todos juntos y pasaron a ser como la paja de la era en el verano, y el viento se los llevó para que no quedara ni rastro de ellos. Pero la piedra que golpeó la estatua se convirtió en una gran montaña y llenó toda la tierra.'],
  ['Daniel 2:36', '”Este es el sueño, y ahora le diremos su interpretación al rey.'],
  ['Daniel 2:37', 'Tú, oh, rey —el rey de reyes a quien el Dios del cielo le dio el reino, el poder, la fuerza y la gloria,'],
  ['Daniel 2:38', 'en cuyas manos entregó hombres dondequiera que vivieran, así como los animales del campo y las aves de los cielos, y a quien hizo gobernante de todos ellos—, tú mismo eres la cabeza de oro.'],
  ['Daniel 2:39', '”Pero después de ti surgirá otro reino inferior a ti. Luego surgirá un tercer reino, uno de cobre, que gobernará toda la tierra.'],
  ['Daniel 2:40', '”El cuarto reino será fuerte como el hierro. Porque, tal como el hierro hace añicos y pulveriza todo lo demás, sí, igual que el hierro que destroza, este hará añicos y destrozará a todos estos reinos.'],
  ['Daniel 2:41', '”Y, tal como los pies y los dedos de los pies que viste eran en parte de barro de alfarero y en parte de hierro, el reino estará dividido, pero tendrá algo de la dureza del hierro, igual que el hierro mezclado con barro húmedo que viste.'],
  ['Daniel 2:42', 'Y, como los dedos de los pies eran en parte de hierro y en parte de barro, del mismo modo el reino será en parte fuerte y en parte frágil.'],
  ['Daniel 2:43', 'Igual que el hierro mezclado con barro húmedo que viste, ellos se mezclarán con el pueblo. Pero no se mantendrán unidos unos a otros, tal como el hierro no se mezcla con el barro.'],
  ['Daniel 2:44', '”En los días de esos reyes, el Dios del cielo establecerá un reino que nunca será destruido ni pasará a manos de ningún otro pueblo. Este reino hará añicos y pondrá fin a todos esos reinos, y será el único que permanecerá para siempre,'],
  ['Daniel 2:45', 'tal como viste que pasaba cuando se cortó una piedra de la montaña, aunque no con manos humanas, y la piedra hizo añicos el hierro, el cobre, el barro, la plata y el oro. El Gran Dios le ha revelado al rey lo que sucederá en el futuro. El sueño es verdadero y su interpretación es digna de confianza”.'],
  ['Daniel 2:46', 'Entonces el rey Nabucodonosor cayó rostro a tierra delante de Daniel y le rindió homenaje. También ordenó que le ofrecieran un regalo e incienso.'],
  ['Daniel 2:47', 'El rey le dijo a Daniel: “El Dios de ustedes es verdaderamente Dios de dioses, Señor de reyes y el que revela secretos, porque pudiste revelar este secreto”.'],
  ['Daniel 2:48', 'Luego, el rey engrandeció a Daniel, le hizo muchos regalos magníficos y lo nombró gobernante de toda la provincia de Babilonia y prefecto principal de todos los sabios de Babilonia.'],
  ['Daniel 2:49', 'A petición de Daniel, el rey puso a Sadrac, Mesac y Abednego a cargo de la administración de la provincia de Babilonia, pero Daniel se quedó en la corte del rey.'],
]
