// Preguntas de Trivia sobre Jeremías 38 y 39, hechas solo con el texto bíblico (TNM) que el
// usuario pegó (src/lib/seedVerses.js). La respuesta correcta es la primera opción (el juego las
// revuelve). Cada una tiene id fijo para no repetirse.
const Q = (n, pregunta, opciones, explicacion, cita) => ({ id: `trivia-jer-${String(n).padStart(2, '0')}`, fields: { pregunta, opciones, respuesta: 0, explicacion, cita } })

export const TRIVIA_JEREMIAS_38_39 = [
  Q(1, '¿Por qué los príncipes querían que mataran a Jeremías?', ['Decían que desmoralizaba a los soldados y al pueblo', 'Decían que había insultado al rey', 'Decían que había robado en el templo', 'Decían que no respetaba el sábado'], 'Le dijeron al rey: "Con las cosas que dice está desmoralizando a los soldados que quedan en esta ciudad y a todo el pueblo".', 'Jeremías 38:4'),
  Q(2, '¿Qué respondió Sedequías cuando los príncipes le pidieron matar a Jeremías?', ['"Ahí lo tienen, está en sus manos"', '"Déjenlo en paz, es profeta de Jehová"', '"Yo mismo lo voy a juzgar"', '"Llévenlo a Babilonia"'], 'Dijo: "Miren, ahí lo tienen, está en sus manos, porque el rey no puede hacer nada para detenerlos a ustedes".', 'Jeremías 38:5'),
  Q(3, '¿En la cisterna de quién arrojaron a Jeremías?', ['De Malkiya, el hijo del rey', 'De Jehonatán', 'De Pasjur', 'De Guedalías'], 'Lo arrojaron "en la cisterna de Malkiya, el hijo del rey, en el Patio de la Guardia".', 'Jeremías 38:6'),
  Q(4, '¿Qué había en la cisterna donde echaron a Jeremías?', ['Solo fango', 'Agua hasta la cintura', 'Nada, estaba seca y limpia', 'Piedras y espinos'], '"En la cisterna no había agua, solo fango, y Jeremías empezó a hundirse en el fango".', 'Jeremías 38:6'),
  Q(5, '¿Quién fue a pedirle al rey que salvara a Jeremías?', ['Ébed-Mélec el etíope', 'Baruc', 'Guedalías', 'Nebuzaradán'], 'Ébed-Mélec, un eunuco de la casa del rey, le dijo: "Lo que esos hombres le han hecho al profeta Jeremías es muy cruel".', 'Jeremías 38:7-9'),
  Q(6, '¿Dónde estaba sentado el rey cuando Ébed-Mélec fue a hablarle?', ['En la Puerta de Benjamín', 'En la Puerta del Medio', 'En el Patio de la Guardia', 'En la cámara del tesoro'], '"El rey estaba sentado en la Puerta de Benjamín".', 'Jeremías 38:7'),
  Q(7, '¿Por qué dijo Ébed-Mélec que Jeremías iba a morir en la cisterna?', ['De hambre, porque ya no quedaba pan en la ciudad', 'Ahogado por el agua', 'Por el frío de la noche', 'Por la espada de los príncipes'], '"Allí se va a morir de hambre, porque ya no queda pan en la ciudad".', 'Jeremías 38:9'),
  Q(8, '¿Cuántos hombres le dijo el rey a Ébed-Mélec que se llevara?', ['30', '3', '10', '70'], '"Llévate de aquí a 30 hombres y saca al profeta Jeremías de la cisterna antes de que se muera".', 'Jeremías 38:10'),
  Q(9, '¿Qué le bajaron a Jeremías para que se los pusiera entre las axilas y las sogas?', ['Trapos viejos y pedazos de tela gastada', 'Pieles de oveja', 'Su propio manto', 'Hojas de palmera'], 'Sacaron "algunos trapos viejos y pedazos de tela gastada" de un lugar debajo de la cámara del tesoro.', 'Jeremías 38:11-12'),
  Q(10, '¿Dónde se quedó Jeremías después de que lo sacaron de la cisterna?', ['En el Patio de la Guardia', 'En su casa en Anatot', 'En el templo', 'En la casa de Ébed-Mélec'], '"Y Jeremías se quedó en el Patio de la Guardia".', 'Jeremías 38:13'),
  Q(11, '¿Qué le dijo Jeremías a Sedequías antes de darle el mensaje en secreto?', ['"Si te lo digo, seguro que me vas a matar"', '"Ya no tengo nada que decirte"', '"Primero sácame de aquí"', '"Jehová ya no me habla"'], '"Si te lo digo, seguro que me vas a matar. Y, si te doy un consejo, no me vas a escuchar".', 'Jeremías 38:15'),
  Q(12, '¿Qué tenía que hacer Sedequías para seguir con vida y que la ciudad no fuera quemada?', ['Rendirse ante los príncipes del rey de Babilonia', 'Huir a Egipto', 'Pelear hasta el final', 'Esconderse en la casa de Jehová'], '"Si te rindes ante los príncipes del rey de Babilonia, tú seguirás con vida, esta ciudad no será quemada con fuego".', 'Jeremías 38:17'),
  Q(13, '¿A quiénes les tenía miedo Sedequías?', ['A los judíos que se habían pasado al bando de los caldeos', 'A los profetas de Jehová', 'A los egipcios', 'A los soldados de su guardia'], '"Les tengo miedo a los judíos que se han pasado al bando de los caldeos".', 'Jeremías 38:19'),
  Q(14, '¿Qué le dijo Sedequías a Jeremías que respondiera si los príncipes le preguntaban?', ['Que le pidió al rey no volver a la casa de Jehonatán a morir', 'Que el rey se iba a rendir', 'Que no había hablado con el rey', 'Que el rey lo iba a dejar libre'], 'Debía decir: "Estaba pidiéndole al rey que no me enviara de vuelta a la casa de Jehonatán a morir allí".', 'Jeremías 38:26'),
  Q(15, '¿Hasta cuándo se quedó Jeremías en el Patio de la Guardia?', ['Hasta el día en que conquistaron Jerusalén', 'Hasta que murió Sedequías', 'Una semana', 'Hasta que regresó de Babilonia'], '"Jeremías permaneció en el Patio de la Guardia hasta el día en que conquistaron Jerusalén".', 'Jeremías 38:28'),
  Q(16, '¿En qué año del rey Sedequías llegó Nabucodonosor a cercar Jerusalén?', ['En el noveno año', 'En el primer año', 'En el año 11', 'En el año 20'], '"En el noveno año del rey Sedequías de Judá, en el décimo mes, el rey Nabucodonosor de Babilonia vino con todo su ejército".', 'Jeremías 39:1'),
  Q(17, '¿En qué año de Sedequías atravesaron la muralla de la ciudad?', ['En el año 11', 'En el noveno año', 'En el año 7', 'En el año 15'], '"En el año 11 de Sedequías, en el cuarto mes, el día nueve del mes, atravesaron la muralla".', 'Jeremías 39:2'),
  Q(18, '¿En qué puerta se sentaron los príncipes del rey de Babilonia?', ['En la Puerta del Medio', 'En la Puerta de Benjamín', 'En la Puerta de las Ovejas', 'En la Puerta del Valle'], '"Todos los príncipes del rey de Babilonia entraron y se sentaron en la Puerta del Medio".', 'Jeremías 39:3'),
  Q(19, '¿Por dónde huyó Sedequías de noche?', ['Por el jardín del rey, por la puerta entre las dos murallas', 'Por la Puerta de Benjamín', 'Por un túnel debajo del templo', 'Por el río, en una barca'], '"Salieron de noche por el jardín del rey, por la puerta que había entre las dos murallas".', 'Jeremías 39:4'),
  Q(20, '¿Dónde alcanzaron los caldeos a Sedequías?', ['En las llanuras desérticas de Jericó', 'En Egipto', 'En Belén', 'En el monte Carmelo'], '"Alcanzaron a Sedequías en las llanuras desérticas de Jericó".', 'Jeremías 39:5'),
  Q(21, '¿Dónde sentenció Nabucodonosor a Sedequías?', ['En Riblá, en la tierra de Hamat', 'En Babilonia', 'En Jerusalén', 'En Nínive'], 'Se lo llevaron "al rey Nabucodonosor de Babilonia en Riblá, en la tierra de Hamat, y allí lo sentenció".', 'Jeremías 39:5'),
  Q(22, '¿Qué le hicieron a Sedequías después de matar a sus hijos ante sus ojos?', ['Lo cegaron y lo sujetaron con grilletes de cobre', 'Lo dejaron libre en Judá', 'Lo mandaron a Egipto', 'Lo pusieron a trabajar en los campos'], '"Luego cegó a Sedequías y lo sujetó con grilletes de cobre para llevárselo a Babilonia".', 'Jeremías 39:6-7'),
  Q(23, '¿Qué hicieron los caldeos con Jerusalén?', ['Quemaron las casas y demolieron las murallas', 'La dejaron igual', 'Solo se llevaron el oro', 'Construyeron un palacio'], '"Los caldeos quemaron la casa del rey y las casas del pueblo, y demolieron las murallas de Jerusalén".', 'Jeremías 39:8'),
  Q(24, '¿Quién era el jefe de la guardia de Babilonia?', ['Nebuzaradán', 'Nebusazbán', 'Nergal-Sarézer', 'Guedalías'], '"Nebuzaradán, el jefe de la guardia, se llevó al destierro en Babilonia al resto de la gente".', 'Jeremías 39:9'),
  Q(25, '¿Qué hizo Nebuzaradán con las personas más pobres de Judá?', ['Las dejó en la tierra y les dio viñas y campos', 'Se las llevó a Babilonia', 'Las mandó a Egipto', 'Las puso en la cárcel'], 'Dejó en Judá "a algunas de las personas más pobres" y "les dio viñas y campos para que trabajaran".', 'Jeremías 39:10'),
  Q(26, '¿Qué orden dio Nabucodonosor acerca de Jeremías?', ['Cuidarlo, no hacerle daño y darle lo que pidiera', 'Llevarlo encadenado a Babilonia', 'Dejarlo en el Patio de la Guardia', 'Ponerlo a servir en su palacio'], '"Ve a buscarlo y cuida de él; no le hagas daño y dale todo lo que te pida".', 'Jeremías 39:11-12'),
  Q(27, '¿A quién le entregaron a Jeremías cuando lo sacaron del Patio de la Guardia?', ['A Guedalías, hijo de Ahicam', 'A Ébed-Mélec', 'A Baruc', 'A Nebuzaradán'], 'Se lo entregaron "a Guedalías, hijo de Ahicam, hijo de Safán, para llevarlo a su casa".', 'Jeremías 39:14'),
  Q(28, '¿Por qué dijo Jehová que rescataría a Ébed-Mélec?', ['Porque confió en Jehová', 'Porque era de la casa del rey', 'Porque era rico', 'Porque nunca tuvo miedo'], '"Sin falta te libraré [...] porque confiaste en mí", afirma Jehová.', 'Jeremías 39:18'),
]
