// Texto bíblico que el usuario pegó en el chat (Traducción del Nuevo Mundo) para guardarlo en su
// "Mi Biblia". Sin las marcas de notas al pie (+ y *). Se guarda versículo por versículo.

export const JEREMIAS_38_39 = [
  ['Jeremías 38:1', 'Sefatías hijo de Matán, Guedalías hijo de Pasjur, Jucal hijo de Selemías y Pasjur hijo de Malkiya oyeron estas palabras que Jeremías le estaba diciendo a todo el pueblo:'],
  ['Jeremías 38:2', '“Esto es lo que dice Jehová: ‘El que se quede en esta ciudad morirá por la espada, el hambre y la peste. Pero el que se rinda ante los caldeos seguirá viviendo; su propia vida será su botín de guerra y él vivirá’.'],
  ['Jeremías 38:3', 'Esto es lo que dice Jehová: ‘Esta ciudad sin falta será entregada en manos del ejército del rey de Babilonia, y él la conquistará’”.'],
  ['Jeremías 38:4', 'Los príncipes le dijeron al rey: “Por favor, haz que maten a este hombre, porque con las cosas que dice está desmoralizando a los soldados que quedan en esta ciudad y a todo el pueblo. Porque este hombre no quiere la paz para este pueblo, sino la calamidad”.'],
  ['Jeremías 38:5', 'El rey Sedequías dijo: “Miren, ahí lo tienen, está en sus manos, porque el rey no puede hacer nada para detenerlos a ustedes”.'],
  ['Jeremías 38:6', 'Así que agarraron a Jeremías y lo arrojaron en la cisterna de Malkiya, el hijo del rey, en el Patio de la Guardia; lo bajaron con sogas. En la cisterna no había agua, solo fango, y Jeremías empezó a hundirse en el fango.'],
  ['Jeremías 38:7', 'Ébed-Mélec el etíope, un eunuco de la casa del rey, se enteró de que habían metido a Jeremías en la cisterna. El rey estaba sentado en la Puerta de Benjamín,'],
  ['Jeremías 38:8', 'así que Ébed-Mélec salió de la casa del rey y le dijo:'],
  ['Jeremías 38:9', '“¡Oh, mi señor el rey, lo que esos hombres le han hecho al profeta Jeremías es muy cruel! Lo han arrojado a la cisterna, y allí se va a morir de hambre, porque ya no queda pan en la ciudad”.'],
  ['Jeremías 38:10', 'Entonces el rey le ordenó a Ébed-Mélec el etíope: “Llévate de aquí a 30 hombres y saca al profeta Jeremías de la cisterna antes de que se muera”.'],
  ['Jeremías 38:11', 'Así que Ébed-Mélec se llevó a los hombres y fue a la casa del rey, a un lugar debajo de la cámara del tesoro, y se llevaron de allí algunos trapos viejos y pedazos de tela gastada, y se los bajaron con sogas a Jeremías en la cisterna.'],
  ['Jeremías 38:12', 'Entonces Ébed-Mélec el etíope le dijo a Jeremías: “Por favor, ponte los trapos y los pedazos de tela entre las axilas y las sogas”. Jeremías lo hizo,'],
  ['Jeremías 38:13', 'y ellos lo fueron subiendo con las sogas y lo sacaron de la cisterna. Y Jeremías se quedó en el Patio de la Guardia.'],
  ['Jeremías 38:14', 'El rey Sedequías mandó traer al profeta Jeremías a la tercera entrada, que está en la casa de Jehová, y el rey le dijo a Jeremías: “Tengo que preguntarte algo. No me ocultes nada”.'],
  ['Jeremías 38:15', 'Jeremías entonces le dijo a Sedequías: “Si te lo digo, seguro que me vas a matar. Y, si te doy un consejo, no me vas a escuchar”.'],
  ['Jeremías 38:16', 'Así que Sedequías le juró a Jeremías a escondidas: “Tan cierto como que vive Jehová, quien nos ha dado esta vida, yo no te voy a matar ni te voy a entregar a estos hombres que quieren quitarte la vida”.'],
  ['Jeremías 38:17', 'Jeremías entonces le dijo a Sedequías: “Esto es lo que dice Jehová, el Dios de los ejércitos, el Dios de Israel: ‘Si te rindes ante los príncipes del rey de Babilonia, tú seguirás con vida, esta ciudad no será quemada con fuego, y tú y los de tu casa no morirán.'],
  ['Jeremías 38:18', 'Pero, si no te rindes ante los príncipes del rey de Babilonia, entonces esta ciudad será entregada en manos de los caldeos, ellos la quemarán con fuego y tú no escaparás de sus manos’”.'],
  ['Jeremías 38:19', 'Entonces el rey Sedequías le dijo a Jeremías: “Les tengo miedo a los judíos que se han pasado al bando de los caldeos. Porque, si me entregan en sus manos, ellos tal vez me traten con crueldad”.'],
  ['Jeremías 38:20', 'Pero Jeremías dijo: “No serás entregado en sus manos. Por favor, obedece la voz de Jehová y haz lo que te estoy diciendo; así te irá bien y seguirás viviendo.'],
  ['Jeremías 38:21', 'Pero, si te niegas a rendirte, Jehová me ha revelado que pasará esto:'],
  ['Jeremías 38:22', '¡mira!, sacarán a todas las mujeres que quedan en la casa del rey de Judá y se las llevarán a los príncipes del rey de Babilonia, y ellas irán diciendo:\n‘Los hombres en los que confiabas te han engañado y te han vencido.\nHan hecho que tus pies se hundan en el fango.\nAhora se han dado la vuelta en retirada’.'],
  ['Jeremías 38:23', 'Y a todas tus esposas y tus hijos los entregarán a los caldeos. Y tú no podrás escapar de sus manos, sino que el rey de Babilonia te capturará, y por tu culpa quemarán con fuego esta ciudad”.'],
  ['Jeremías 38:24', 'Luego Sedequías le dijo a Jeremías: “No le digas nada de esto a nadie, para que no mueras.'],
  ['Jeremías 38:25', 'Y, si los príncipes se enteran de que hablé contigo y vienen a decirte ‘Por favor, cuéntanos lo que le dijiste al rey. No nos ocultes nada y no te mataremos. ¿Y qué te dijo el rey a ti?’,'],
  ['Jeremías 38:26', 'entonces tienes que responderles ‘Estaba pidiéndole al rey que no me enviara de vuelta a la casa de Jehonatán a morir allí’”.'],
  ['Jeremías 38:27', 'Tiempo después, todos los príncipes vinieron a ver a Jeremías y lo interrogaron. Él les dijo todo lo que el rey le había mandado decir. Así que ellos no le preguntaron nada más, porque ninguno había escuchado la conversación.'],
  ['Jeremías 38:28', 'Jeremías permaneció en el Patio de la Guardia hasta el día en que conquistaron Jerusalén; él todavía estaba allí cuando Jerusalén fue conquistada.'],

  ['Jeremías 39:1', 'En el noveno año del rey Sedequías de Judá, en el décimo mes, el rey Nabucodonosor de Babilonia vino con todo su ejército a Jerusalén y la cercaron.'],
  ['Jeremías 39:2', 'En el año 11 de Sedequías, en el cuarto mes, el día nueve del mes, atravesaron la muralla de la ciudad.'],
  ['Jeremías 39:3', 'Y todos los príncipes del rey de Babilonia entraron y se sentaron en la Puerta del Medio. Eran el samgar Nergal-Sarézer, el rabsarís Nebo-Sarsekim, el rabmag Nergal-Sarézer y todos los demás príncipes del rey de Babilonia.'],
  ['Jeremías 39:4', 'Cuando el rey Sedequías de Judá y todos los soldados los vieron, huyeron de la ciudad. Salieron de noche por el jardín del rey, por la puerta que había entre las dos murallas, y continuaron por el camino del Arabá.'],
  ['Jeremías 39:5', 'Pero el ejército de los caldeos los persiguió, y alcanzaron a Sedequías en las llanuras desérticas de Jericó. Lo capturaron y se lo llevaron al rey Nabucodonosor de Babilonia en Riblá, en la tierra de Hamat, y allí lo sentenció.'],
  ['Jeremías 39:6', 'El rey de Babilonia hizo que mataran a los hijos de Sedequías allí en Riblá, ante sus propios ojos. Y el rey de Babilonia también hizo que mataran a todos los nobles de Judá.'],
  ['Jeremías 39:7', 'Luego cegó a Sedequías y lo sujetó con grilletes de cobre para llevárselo a Babilonia.'],
  ['Jeremías 39:8', 'Entonces los caldeos quemaron la casa del rey y las casas del pueblo, y demolieron las murallas de Jerusalén.'],
  ['Jeremías 39:9', 'Nebuzaradán, el jefe de la guardia, se llevó al destierro en Babilonia al resto de la gente que quedaba en la ciudad, a los desertores que se habían pasado a su bando y a todos los que quedaban.'],
  ['Jeremías 39:10', 'Pero Nebuzaradán, el jefe de la guardia, dejó en la tierra de Judá a algunas de las personas más pobres, las que no tenían nada. Aquel día también les dio viñas y campos para que trabajaran.'],
  ['Jeremías 39:11', 'Ahora bien, el rey Nabucodonosor de Babilonia le dio a Nebuzaradán, el jefe de la guardia, estas órdenes acerca de Jeremías:'],
  ['Jeremías 39:12', '“Ve a buscarlo y cuida de él; no le hagas daño y dale todo lo que te pida”.'],
  ['Jeremías 39:13', 'Así que Nebuzaradán —el jefe de la guardia—, el rabsarís Nebusazbán, el rabmag Nergal-Sarézer y todos los hombres principales del rey de Babilonia mandaron'],
  ['Jeremías 39:14', 'sacar a Jeremías del Patio de la Guardia y se lo entregaron a Guedalías, hijo de Ahicam, hijo de Safán, para llevarlo a su casa. Así que Jeremías vivió entre el pueblo.'],
  ['Jeremías 39:15', 'Cuando Jeremías estuvo preso en el Patio de la Guardia, recibió estas palabras de Jehová:'],
  ['Jeremías 39:16', '“Ve y dile a Ébed-Mélec el etíope: ‘Esto es lo que dice Jehová de los ejércitos, el Dios de Israel: “Voy a cumplir mis palabras sobre esta ciudad, palabras de calamidad y no de cosas buenas, y ese día las verás cumplirse”’.'],
  ['Jeremías 39:17', '”‘Pero yo te rescataré ese día —afirma Jehová—, y no serás entregado en manos de los hombres que te dan miedo’.'],
  ['Jeremías 39:18', '”‘Porque sin falta te libraré, y no caerás a espada. Tu propia vida será tu botín de guerra, porque confiaste en mí’, afirma Jehová”.'],
]
