// Memoria Bíblica: personajes en orden de la historia bíblica, agrupados en 8 mundos.
// n = nombre, t = quién fue (corto), c = cita, p = dos pistas en primera persona (de difícil a fácil),
// d = lo que hizo (sin decir el nombre). El orden de la lista es el orden histórico aproximado.

export const WORLDS = [
  { id: 1, name: 'Los comienzos', books: 'Génesis 1-11' },
  { id: 2, name: 'Los patriarcas', books: 'Génesis 12-50 y Job' },
  { id: 3, name: 'Éxodo y desierto', books: 'Éxodo a Deuteronomio' },
  { id: 4, name: 'Conquista y jueces', books: 'Josué, Jueces, Rut y 1 Samuel' },
  { id: 5, name: 'El reino unido', books: '1 y 2 Samuel, 1 Reyes' },
  { id: 6, name: 'El reino dividido', books: 'Reyes, Crónicas y profetas' },
  { id: 7, name: 'Exilio y regreso', books: 'Daniel, Esdras, Nehemías y Ester' },
  { id: 8, name: 'Jesús y la congregación', books: 'Evangelios y Hechos' },
]

const C = (w, n, t, c, p, d) => ({ w, n, t, c, p, d })

const LIST = [
  // 1 · Los comienzos
  C(1, 'Adán', 'El primer hombre', 'Génesis 2:7', ['Jehová me formó del polvo de la tierra.', 'Les puse nombre a los animales.'], 'Desobedeció a Jehová al comer del fruto prohibido.'),
  C(1, 'Eva', 'La primera mujer', 'Génesis 3:20', ['Fui hecha de una costilla.', 'La serpiente me engañó.'], 'Fue llamada así porque sería la madre de todos los que vivieran.'),
  C(1, 'Caín', 'El primer asesino', 'Génesis 4:8', ['Cultivaba la tierra.', 'Jehová no aceptó mi ofrenda y me enfurecí.'], 'Mató a su propio hermano por envidia.'),
  C(1, 'Abel', 'Primer siervo fiel de Jehová', 'Hebreos 11:4', ['Era pastor de ovejas.', 'Ofrecí a Jehová de los primogénitos de mi rebaño.'], 'Su hermano lo mató por envidia.'),
  C(1, 'Set', 'Hijo de Adán en lugar de Abel', 'Génesis 4:25', ['Mi madre dijo que Dios le dio otro hijo en lugar del que murió.', 'Mi padre tenía 130 años cuando nací.'], 'Nació después de la muerte de Abel y fue padre de Enós.'),
  C(1, 'Enoc', 'Caminó con Dios', 'Génesis 5:24', ['Profeticé contra los malvados.', 'Viví 365 años.'], 'Caminó con Dios, y Dios se lo llevó.'),
  C(1, 'Matusalén', 'El hombre más longevo', 'Génesis 5:27', ['Mi padre fue Enoc.', 'Fui abuelo de Noé.'], 'Vivió 969 años.'),
  C(1, 'Noé', 'Construyó el arca', 'Génesis 6:14', ['Fui predicador de justicia.', 'Mis hijos fueron Sem, Cam y Jafet.'], 'Salvó a su familia del Diluvio.'),
  C(1, 'Sem', 'Hijo de Noé', 'Génesis 9:26', ['Sobreviví al Diluvio con mi familia.', 'Abrahán fue uno de mis descendientes.'], 'Noé llamó a Jehová "el Dios de" él.'),
  C(1, 'Nemrod', 'Poderoso cazador', 'Génesis 10:9', ['Fui bisnieto de Noé.', 'Mi reino comenzó en Babel.'], 'Fue un poderoso cazador en oposición a Jehová.'),

  // 2 · Los patriarcas
  C(2, 'Abrahán', 'Amigo de Jehová', 'Santiago 2:23', ['Salí de Ur de los caldeos.', 'Estuve dispuesto a ofrecer a mi hijo.'], 'Es llamado el padre de todos los que tienen fe.'),
  C(2, 'Sara', 'Esposa de Abrahán', 'Génesis 21:2', ['Me reí cuando oí que tendría un hijo.', 'Fui madre a los 90 años.'], 'Fue madre de Isaac en su vejez.'),
  C(2, 'Lot', 'Sobrino de Abrahán', 'Génesis 19:16', ['Vivía en Sodoma.', 'Unos ángeles nos tomaron de la mano para sacarnos.'], 'Su esposa miró atrás y se convirtió en columna de sal.'),
  C(2, 'Melquisedec', 'Rey y sacerdote de Salem', 'Génesis 14:18', ['Le llevé pan y vino a Abrahán.', 'Abrahán me dio la décima parte de todo.'], 'Fue rey y sacerdote a la vez, como Jesús.'),
  C(2, 'Agar', 'Sierva egipcia de Sara', 'Génesis 16:1', ['Huí al desierto.', 'Un ángel me encontró junto a una fuente.'], 'Fue madre de Ismael.'),
  C(2, 'Ismael', 'Hijo de Abrahán y Agar', 'Génesis 21:18', ['Me burlé de mi hermano menor.', 'Viví en el desierto y fui arquero.'], 'Dios prometió hacer de él una gran nación.'),
  C(2, 'Isaac', 'El hijo de la promesa', 'Génesis 21:3', ['Cargué la leña para el sacrificio.', 'Mi esposa fue Rebeca.'], 'Nació cuando su padre tenía 100 años.'),
  C(2, 'Rebeca', 'Esposa de Isaac', 'Génesis 24:67', ['Les di agua a los camellos de un siervo.', 'Fui madre de gemelos.'], 'Aceptó irse a una tierra lejana para casarse.'),
  C(2, 'Esaú', 'Vendió su primogenitura', 'Génesis 25:33', ['Era cazador y muy velludo.', 'Cambié algo valioso por un plato de guiso.'], 'Le vendió su primogenitura a su hermano gemelo.'),
  C(2, 'Jacob', 'Llamado Israel', 'Génesis 32:28', ['Luché con un ángel.', 'Tuve 12 hijos.'], 'Dios le cambió el nombre a Israel.'),
  C(2, 'Lea', 'Primera esposa de Jacob', 'Génesis 29:23', ['Mi padre engañó a mi esposo para que se casara conmigo.', 'Fui madre de Leví y de Judá.'], 'Fue madre de seis de los hijos de Jacob.'),
  C(2, 'Raquel', 'Esposa amada de Jacob', 'Génesis 29:18', ['Mi padre era Labán.', 'Fui madre de José y de Benjamín.'], 'Jacob trabajó siete años por ella.'),
  C(2, 'José', 'Vendido por sus hermanos', 'Génesis 37:28', ['Mi padre me regaló una túnica especial.', 'Interpreté los sueños del faraón.'], 'Llegó a administrar Egipto y salvó a su familia del hambre.'),
  C(2, 'Judá', 'Hijo de Jacob', 'Génesis 49:10', ['Propuse vender a mi hermano en vez de matarlo.', 'Me ofrecí como esclavo en lugar de mi hermano menor.'], 'De su tribu vendrían el rey David y Jesús.'),
  C(2, 'Benjamín', 'El hijo menor de Jacob', 'Génesis 35:18', ['Mi madre murió cuando nací.', 'Encontraron una copa de plata en mi costal.'], 'Era el hermano menor de José.'),
  C(2, 'Job', 'Mantuvo su integridad', 'Job 27:5', ['Perdí a mis hijos, mis bienes y mi salud.', 'Vivía en la tierra de Uz.'], 'Satanás dijo que servía a Dios por interés, y él demostró que no.'),

  // 3 · Éxodo y desierto
  C(3, 'Jocabed', 'Madre de Moisés', 'Éxodo 6:20', ['Escondí a mi bebé tres meses.', 'Lo puse en una canasta en el río Nilo.'], 'La hija del faraón le pagó por criar a su propio hijo.'),
  C(3, 'Moisés', 'Sacó a Israel de Egipto', 'Éxodo 3:10', ['Me crie en la casa del faraón.', 'Dios me habló desde una zarza que ardía.'], 'Recibió los Diez Mandamientos en el monte Sinaí.'),
  C(3, 'Aarón', 'Primer sumo sacerdote', 'Éxodo 28:1', ['Hablaba al pueblo en nombre de mi hermano.', 'Mi vara floreció.'], 'Hizo un becerro de oro cuando el pueblo se lo pidió.'),
  C(3, 'Míriam', 'Profetisa, hermana de Moisés', 'Éxodo 15:20', ['Vigilé a mi hermanito en el río.', 'Dirigí a las mujeres con pandero y cantos.'], 'Por criticar a Moisés quedó leprosa un tiempo.'),
  C(3, 'Jetró', 'Suegro de Moisés', 'Éxodo 18:1', ['Fui sacerdote de Madián.', 'Aconsejé a mi yerno que repartiera el trabajo.'], 'Le recomendó a Moisés nombrar jefes sobre miles, cientos y decenas.'),
  C(3, 'Bezalel', 'Artesano del tabernáculo', 'Éxodo 31:2', ['Dios me llenó de su espíritu para trabajar el oro, la plata y la madera.', 'Hice el arca del pacto.'], 'Dirigió la construcción del tabernáculo.'),
  C(3, 'Coré', 'Se rebeló contra Moisés', 'Números 16:1', ['Era levita.', 'La tierra se abrió y nos tragó.'], 'Se rebeló contra Moisés y Aarón por envidia.'),
  C(3, 'Caleb', 'Espía fiel', 'Números 14:24', ['Fui uno de los 12 espías.', 'A los 85 años pedí conquistar una región montañosa.'], 'Siguió a Jehová de todo corazón y entró en la Tierra Prometida.'),
  C(3, 'Balaam', 'Profeta que quiso maldecir a Israel', 'Números 22:28', ['Un rey me pagó para maldecir a un pueblo.', 'Mi burra me habló.'], 'Jehová lo obligó a bendecir en vez de maldecir.'),
  C(3, 'Finehás', 'Sacerdote celoso', 'Números 25:11', ['Fui nieto de Aarón.', 'Detuve una plaga actuando con celo por Jehová.'], 'No toleró que nadie compitiera con Jehová.'),

  // 4 · Conquista y jueces
  C(4, 'Josué', 'Dirigió la conquista de Canaán', 'Josué 1:9', ['Fui uno de los dos espías fieles.', 'Los muros de Jericó cayeron cuando marchamos.'], 'Dijo: "Yo y mi casa serviremos a Jehová".'),
  C(4, 'Rahab', 'Escondió a los espías', 'Josué 2:1', ['Vivía en el muro de Jericó.', 'Colgué un cordón rojo en mi ventana.'], 'Por su fe se salvó con su familia y llegó a ser antepasada de Jesús.'),
  C(4, 'Acán', 'Robó en Jericó', 'Josué 7:1', ['Escondí plata, oro y un manto bajo mi tienda.', 'Por mi culpa Israel perdió en Hai.'], 'Su codicia causó una derrota a Israel.'),
  C(4, 'Débora', 'Profetisa y jueza', 'Jueces 4:4', ['Juzgaba debajo de una palmera.', 'Animé a Barac a pelear contra Sísara.'], 'Junto con Barac cantó una canción de victoria.'),
  C(4, 'Barac', 'Venció a Sísara', 'Jueces 4:14', ['Dije que iría a la batalla solo si una profetisa iba conmigo.', 'Bajé del monte Tabor con 10.000 hombres.'], 'Aparece en Hebreos 11 entre los hombres de fe.'),
  C(4, 'Jael', 'Acabó con Sísara', 'Jueces 4:21', ['Le di leche a un general cansado.', 'Usé una estaca de la tienda.'], 'Acabó con el jefe del ejército enemigo.'),
  C(4, 'Gedeón', 'Venció con 300 hombres', 'Jueces 7:7', ['Puse un vellón de lana para pedir una señal.', 'Mis hombres usaron trompetas, jarras y antorchas.'], 'Jehová redujo su ejército para que nadie dijera que ganó por su fuerza.'),
  C(4, 'Jefté', 'Juez que hizo un voto', 'Jueces 11:30', ['Mis hermanos me echaron de la casa.', 'Mi hija cumplió mi promesa a Jehová.'], 'Su hija sirvió a Jehová toda su vida sin casarse.'),
  C(4, 'Sansón', 'El juez más fuerte', 'Jueces 16:17', ['Maté a un león con mis manos.', 'Mi fuerza estaba ligada a mi voto de nazareo.'], 'Derribó el templo de Dagón sobre los filisteos.'),
  C(4, 'Dalila', 'Traicionó a Sansón', 'Jueces 16:4', ['Los filisteos me ofrecieron mucha plata.', 'Insistí hasta que me contó su secreto.'], 'Hizo que le cortaran el cabello a Sansón.'),
  C(4, 'Noemí', 'Suegra de Rut', 'Rut 1:20', ['Perdí a mi esposo y a mis dos hijos en Moab.', 'Pedí que me llamaran Mara, que significa "amarga".'], 'Su nuera se negó a dejarla sola.'),
  C(4, 'Rut', 'Leal a su suegra', 'Rut 1:16', ['Era moabita.', 'Recogía espigas en el campo de Boaz.'], 'Dijo: "Tu pueblo será mi pueblo, y tu Dios, mi Dios".'),
  C(4, 'Boaz', 'Se casó con Rut', 'Rut 4:13', ['Tenía un campo en Belén.', 'Pedí a mis trabajadores que dejaran espigas para una mujer trabajadora.'], 'Fue bisabuelo del rey David.'),
  C(4, 'Ana', 'Madre de Samuel', '1 Samuel 1:27', ['Oré con tanta emoción que el sacerdote pensó que estaba borracha.', 'Cada año le hacía una túnica a mi hijo.'], 'Cumplió su promesa y llevó a su hijo a servir en el tabernáculo.'),
  C(4, 'Elí', 'Sumo sacerdote en Siló', '1 Samuel 4:18', ['Pensé que una mujer que oraba estaba borracha.', 'No corregí a mis hijos Hofní y Finehás.'], 'Murió al oír que habían capturado el arca.'),
  C(4, 'Samuel', 'Profeta desde niño', '1 Samuel 3:10', ['Jehová me llamó de noche cuando era niño.', 'Ungí a los dos primeros reyes de Israel.'], 'Dijo: "Habla, que tu siervo escucha".'),

  // 5 · El reino unido
  C(5, 'Saúl', 'Primer rey de Israel', '1 Samuel 10:1', ['Era más alto que todos.', 'Me escondí entre el equipaje cuando me iban a presentar.'], 'Jehová lo rechazó por desobedecer.'),
  C(5, 'Jonatán', 'Amigo leal de David', '1 Samuel 18:1', ['Mi padre era el rey.', 'Le di a mi amigo mi manto, mi espada y mi arco.'], 'Prefirió la amistad de David a ser rey.'),
  C(5, 'David', 'Rey según el corazón de Jehová', '1 Samuel 16:13', ['Era pastor y tocaba el arpa.', 'Vencí a un gigante con una honda.'], 'Escribió muchos de los Salmos.'),
  C(5, 'Goliat', 'Gigante filisteo', '1 Samuel 17:4', ['Medía más de dos metros y medio.', 'Desafié al ejército de Israel 40 días.'], 'Cayó con una piedra lanzada con honda.'),
  C(5, 'Mical', 'Hija de Saúl, esposa de David', '1 Samuel 18:20', ['Ayudé a mi esposo a escapar por una ventana.', 'Me burlé de él cuando danzó delante del arca.'], 'Puso una estatuilla en la cama para engañar a los soldados.'),
  C(5, 'Abigail', 'Mujer sabia y humilde', '1 Samuel 25:3', ['Mi esposo Nabal era duro y malvado.', 'Llevé comida para calmar a un futuro rey.'], 'Evitó que David se vengara y después se casó con él.'),
  C(5, 'Natán', 'Profeta que corrigió a David', '2 Samuel 12:7', ['Le conté al rey la historia de una ovejita.', 'Le dije: "¡Tú eres ese hombre!".'], 'Ayudó a que Salomón llegara a ser rey.'),
  C(5, 'Urías', 'Soldado leal', '2 Samuel 11:11', ['Era hitita y soldado de David.', 'No quise ir a mi casa mientras el ejército estaba en campaña.'], 'David ordenó ponerlo al frente de la batalla para que muriera.'),
  C(5, 'Bat-seba', 'Madre de Salomón', '2 Samuel 12:24', ['Mi primer esposo fue Urías el hitita.', 'El rey me vio desde su azotea.'], 'Fue madre del rey Salomón.'),
  C(5, 'Absalón', 'Hijo rebelde de David', '2 Samuel 15:6', ['Me robé el corazón del pueblo.', 'Mi cabello se enredó en un árbol.'], 'Se rebeló contra su padre para quitarle el trono.'),
  C(5, 'Joab', 'Jefe del ejército de David', '2 Samuel 18:14', ['Era sobrino de David.', 'Maté al hijo del rey aunque el rey pidió que no le hicieran daño.'], 'Era valiente, pero vengativo.'),
  C(5, 'Salomón', 'El rey más sabio', '1 Reyes 3:9', ['Pedí a Jehová un corazón obediente para juzgar.', 'Construí el templo en Jerusalén.'], 'Escribió muchos proverbios, pero al final sus esposas lo apartaron de Jehová.'),
  C(5, 'La reina de Seba', 'Visitó a Salomón', '1 Reyes 10:1', ['Viajé desde muy lejos con camellos cargados de regalos.', 'Llegué con preguntas difíciles para el rey.'], 'Dijo que no le habían contado ni la mitad de su sabiduría.'),

  // 6 · El reino dividido
  C(6, 'Roboam', 'Hijo de Salomón', '1 Reyes 12:14', ['No hice caso a los consejos de los ancianos.', 'Por mi dureza, diez tribus se separaron.'], 'En su reinado el reino se dividió en dos.'),
  C(6, 'Jeroboán', 'Primer rey de las diez tribus', '1 Reyes 12:28', ['Fui siervo de Salomón.', 'Hice dos becerros de oro en Betel y Dan.'], 'Llevó al pueblo a adorar ídolos para que no fueran a Jerusalén.'),
  C(6, 'Acab', 'Rey malvado de Israel', '1 Reyes 21:25', ['Mi esposa era Jezabel.', 'Me quedé con la viña de Nabot.'], 'Promovió la adoración a Baal en Israel.'),
  C(6, 'Jezabel', 'Reina malvada', '1 Reyes 19:2', ['Era hija del rey de Sidón.', 'Perseguí a los profetas de Jehová.'], 'Amenazó de muerte al profeta Elías.'),
  C(6, 'Elías', 'Profeta de fuego', '1 Reyes 18:38', ['Unos cuervos me llevaban comida.', 'Desafié a los profetas de Baal en el monte Carmelo.'], 'Fue llevado en una tormenta de viento.'),
  C(6, 'Eliseo', 'Sucesor de Elías', '2 Reyes 2:9', ['Pedí dos partes del espíritu de mi maestro.', 'Salieron osos cuando unos muchachos se burlaron de mí.'], 'Resucitó al hijo de una mujer sunamita.'),
  C(6, 'Naamán', 'General sanado de lepra', '2 Reyes 5:14', ['Era jefe del ejército de Siria.', 'Me bañé siete veces en el Jordán.'], 'Una niña israelita le dijo dónde encontrar curación.'),
  C(6, 'Jehosafat', 'Rey que confió en Jehová', '2 Crónicas 20:12', ['Un ejército enorme vino contra mí.', 'Mandé a los cantores delante del ejército.'], 'Dijo: "No sabemos qué hacer, pero nuestros ojos están puestos en ti".'),
  C(6, 'Jonás', 'Profeta que huyó', 'Jonás 1:3', ['Me subí a un barco que iba en dirección contraria.', 'Pasé tres días dentro de un gran pez.'], 'Predicó en Nínive y la ciudad se arrepintió.'),
  C(6, 'Isaías', 'Profeta de Judá', 'Isaías 6:8', ['Dije: "¡Aquí estoy! ¡Envíame a mí!".', 'Profeticé el nombre de Ciro mucho antes de que naciera.'], 'Profetizó mucho sobre el Mesías.'),
  C(6, 'Ezequías', 'Rey fiel de Judá', '2 Reyes 18:5', ['Destruí la serpiente de cobre que adoraban.', 'Jehová me dio 15 años más de vida.'], 'Un ángel acabó con el ejército asirio que lo amenazaba.'),
  C(6, 'Josías', 'Rey joven que buscó a Jehová', '2 Reyes 22:1', ['Llegué a ser rey a los 8 años.', 'Encontraron el libro de la Ley mientras reparaban el templo.'], 'Limpió el país de ídolos.'),
  C(6, 'Jeremías', 'Profeta valiente', 'Jeremías 1:6', ['Le dije a Jehová que era solo un muchacho.', 'Me echaron en una cisterna de lodo.'], 'Anunció la destrucción de Jerusalén aunque lo trataran como traidor.'),
  C(6, 'Baruc', 'Secretario de Jeremías', 'Jeremías 36:4', ['Escribía lo que el profeta me dictaba.', 'El rey quemó el rollo que yo había escrito.'], 'Jehová le dijo que no buscara grandes cosas para sí.'),
  C(6, 'Ebed-melec', 'Etíope que salvó a Jeremías', 'Jeremías 38:7', ['Trabajaba en el palacio del rey.', 'Usé trapos viejos para que las sogas no lastimaran a alguien.'], 'Jehová lo protegió porque confió en él.'),
  C(6, 'Sedequías', 'Último rey de Judá', 'Jeremías 39:7', ['Le pedía consejo a un profeta en secreto.', 'Tuve miedo de lo que dirían de mí.'], 'Le sacaron los ojos y lo llevaron a Babilonia.'),

  // 7 · Exilio y regreso
  C(7, 'Ezequiel', 'Profeta en el exilio', 'Ezequiel 37:1', ['Era sacerdote y me llevaron a Babilonia.', 'Vi un valle lleno de huesos secos.'], 'Jehová lo nombró atalaya de Israel.'),
  C(7, 'Daniel', 'Fiel en Babilonia', 'Daniel 6:10', ['Me negué a comer la comida del rey.', 'Me echaron al foso de los leones.'], 'Oraba tres veces al día aunque estaba prohibido.'),
  C(7, 'Sadrac, Mesac y Abednego', 'Los tres amigos de Daniel', 'Daniel 3:17', ['No nos inclinamos ante la estatua de oro.', 'Nos echaron a un horno ardiente.'], 'Salieron del fuego sin oler a humo.'),
  C(7, 'Nabucodonosor', 'Rey de Babilonia', 'Daniel 4:30', ['Destruí Jerusalén.', 'Soñé con una enorme estatua de varios metales.'], 'Por su orgullo vivió como un animal un tiempo.'),
  C(7, 'Belsasar', 'Rey de la última fiesta', 'Daniel 5:5', ['Usé las copas del templo de Jerusalén en una fiesta.', 'Una mano escribió en la pared de mi palacio.'], 'Esa misma noche lo mataron y cayó Babilonia.'),
  C(7, 'Ciro', 'Rey persa que liberó a los judíos', 'Esdras 1:2', ['Un profeta dijo mi nombre siglos antes de que naciera.', 'Conquisté Babilonia.'], 'Ordenó reconstruir el templo de Jerusalén.'),
  C(7, 'Zorobabel', 'Gobernador que reconstruyó el templo', 'Zacarías 4:9', ['Guie al primer grupo que regresó de Babilonia.', 'Puse los cimientos del templo.'], 'El profeta Zacarías dijo que él terminaría el templo.'),
  C(7, 'Ageo', 'Profeta de la reconstrucción', 'Ageo 1:4', ['Le pregunté al pueblo si era tiempo de vivir en casas lujosas.', 'Animé a terminar el templo.'], 'Animó al pueblo a poner primero la casa de Jehová.'),
  C(7, 'Ester', 'Reina que salvó a su pueblo', 'Ester 4:16', ['Me crio mi primo.', 'Me presenté ante el rey sin que me llamara.'], 'Dijo: "Si tengo que morir, moriré".'),
  C(7, 'Mardoqueo', 'Primo de Ester', 'Ester 2:7', ['Descubrí un plan para matar al rey.', 'No me inclinaba ante un alto funcionario.'], 'Terminó honrado por el rey en lugar de ser colgado.'),
  C(7, 'Hamán', 'Enemigo de los judíos', 'Ester 3:6', ['Me enfurecía que alguien no se inclinara ante mí.', 'Preparé un madero de 50 codos.'], 'Lo colgaron en el madero que preparó para otro.'),
  C(7, 'Esdras', 'Copista experto en la Ley', 'Esdras 7:10', ['Preparé mi corazón para consultar la Ley.', 'Leí la Ley al pueblo desde una plataforma de madera.'], 'Enseñó la Ley de Jehová en Israel.'),
  C(7, 'Nehemías', 'Reconstruyó los muros', 'Nehemías 2:5', ['Era copero del rey persa.', 'Oré en silencio antes de responderle al rey.'], 'Los muros de Jerusalén se terminaron en 52 días.'),

  // 8 · Jesús y la congregación
  C(8, 'Zacarías', 'Padre de Juan el Bautista', 'Lucas 1:13', ['Era sacerdote y servía en el templo.', 'Me quedé mudo por no creerle a un ángel.'], 'Volvió a hablar al ponerle nombre a su hijo.'),
  C(8, 'Elisabet', 'Madre de Juan el Bautista', 'Lucas 1:41', ['Tuve un hijo cuando ya era anciana.', 'Mi bebé saltó en mi vientre cuando llegó mi pariente María.'], 'Se llenó de espíritu santo al saludar a la madre de Jesús.'),
  C(8, 'María', 'Madre de Jesús', 'Lucas 1:38', ['Un ángel me visitó en Nazaret.', 'Di a luz en Belén.'], 'Dijo: "¡Aquí está la esclava de Jehová!".'),
  C(8, 'José, esposo de María', 'Carpintero de Nazaret', 'Mateo 1:24', ['Un ángel me habló en sueños.', 'Huí a Egipto con mi familia.'], 'Crio a Jesús como si fuera su hijo.'),
  C(8, 'Herodes el Grande', 'Rey cuando nació Jesús', 'Mateo 2:16', ['Unos astrólogos me preguntaron por el rey de los judíos.', 'Ordené matar a los niños de Belén.'], 'Quiso acabar con Jesús cuando era bebé.'),
  C(8, 'Juan el Bautista', 'Preparó el camino', 'Mateo 3:11', ['Comía langostas y miel silvestre.', 'Bauticé a Jesús en el Jordán.'], 'Herodes ordenó que le cortaran la cabeza.'),
  C(8, 'Andrés', 'Hermano de Pedro', 'Juan 1:41', ['Fui discípulo de Juan el Bautista.', 'Le dije a mi hermano: "Hemos encontrado al Mesías".'], 'Llevó a su hermano a Jesús.'),
  C(8, 'Pedro', 'Apóstol pescador', 'Mateo 16:16', ['Caminé sobre el agua un momento.', 'Negué a mi Maestro tres veces.'], 'Dio el discurso en el Pentecostés del año 33.'),
  C(8, 'Santiago', 'Apóstol, hijo de Zebedeo', 'Hechos 12:2', ['Jesús nos llamó a mi hermano y a mí "Hijos del Trueno".', 'Era pescador con mi padre.'], 'Fue el primer apóstol en morir como mártir.'),
  C(8, 'Juan', 'El apóstol amado', 'Juan 21:20', ['Jesús me encargó cuidar a su madre.', 'Escribí Apocalipsis en la isla de Patmos.'], 'Escribió un Evangelio y tres cartas.'),
  C(8, 'Mateo', 'Cobrador de impuestos', 'Mateo 9:9', ['Estaba sentado en la oficina de impuestos.', 'Hice un gran banquete para Jesús.'], 'Escribió el primer Evangelio.'),
  C(8, 'Tomás', 'El apóstol que dudó', 'Juan 20:25', ['Dije que no creería si no veía las marcas de los clavos.', 'También me llamaban el Gemelo.'], 'Al ver a Jesús dijo: "¡Mi Señor y mi Dios!".'),
  C(8, 'Nicodemo', 'Fariseo que visitó a Jesús de noche', 'Juan 3:2', ['Era maestro de Israel.', 'Llevé mirra y áloe para el entierro de Jesús.'], 'Jesús le habló de nacer de nuevo.'),
  C(8, 'Zaqueo', 'Se subió a un árbol', 'Lucas 19:5', ['Era bajo de estatura.', 'Prometí devolver cuatro veces lo que había robado.'], 'Jesús se hospedó en su casa.'),
  C(8, 'Marta', 'Hermana de Lázaro', 'Lucas 10:41', ['Me preocupaba mucho por servir la comida.', 'Jesús me dijo: "Yo soy la resurrección y la vida".'], 'Su hermana María prefirió sentarse a escuchar a Jesús.'),
  C(8, 'Lázaro', 'Resucitado por Jesús', 'Juan 11:43', ['Vivía en Betania con mis hermanas.', 'Estuve cuatro días en la tumba.'], 'Jesús lloró antes de resucitarlo.'),
  C(8, 'Judas Iscariote', 'Traicionó a Jesús', 'Mateo 26:15', ['Cuidaba la caja del dinero y robaba de ella.', 'Me pagaron 30 piezas de plata.'], 'Entregó a Jesús con un beso.'),
  C(8, 'Poncio Pilato', 'Gobernador romano', 'Juan 18:38', ['Pregunté: "¿Qué es la verdad?".', 'Me lavé las manos delante del pueblo.'], 'Entregó a Jesús para que lo ejecutaran aunque sabía que era inocente.'),
  C(8, 'María Magdalena', 'Primera en ver a Jesús resucitado', 'Juan 20:16', ['Jesús me libró de siete demonios.', 'Estuve junto al madero cuando murió mi Señor.'], 'Pensó que Jesús resucitado era el jardinero.'),
  C(8, 'Ananías y Safira', 'Mintieron sobre una venta', 'Hechos 5:1', ['Vendimos un terreno.', 'Dijimos que dábamos todo, pero nos quedamos con una parte.'], 'Murieron por mentirle a Dios.'),
  C(8, 'Bernabé', 'Hijo de Consuelo', 'Hechos 4:36', ['Vendí un campo y les di el dinero a los apóstoles.', 'Acompañé a Pablo en su primer viaje.'], 'Su sobrenombre significa "Hijo de Consuelo".'),
  C(8, 'Esteban', 'Primer mártir cristiano', 'Hechos 7:59', ['Me eligieron para repartir comida a las viudas.', 'Antes de morir vi a Jesús a la derecha de Dios.'], 'Murió apedreado y perdonó a quienes lo mataban.'),
  C(8, 'Felipe', 'Evangelizador', 'Hechos 8:35', ['Prediqué en Samaria.', 'Le expliqué Isaías a un funcionario etíope en su carro.'], 'Bautizó al eunuco etíope.'),
  C(8, 'Pablo', 'Apóstol a las naciones', 'Hechos 9:15', ['Antes perseguía a los cristianos.', 'Quedé ciego en el camino a Damasco.'], 'Escribió 14 cartas de las Escrituras Griegas.'),
  C(8, 'Dorcas', 'Discípula resucitada', 'Hechos 9:36', ['Hacía ropa para las viudas.', 'También me llamaban Tabita.'], 'Pedro la resucitó en Jope.'),
  C(8, 'Cornelio', 'Primer cristiano no judío', 'Hechos 10:1', ['Era oficial del ejército romano.', 'Un ángel me dijo que llamara a Pedro.'], 'Él y su familia recibieron espíritu santo antes de bautizarse.'),
  C(8, 'Juan Marcos', 'Escribió un Evangelio', 'Hechos 12:25', ['Dejé a Pablo y Bernabé a mitad de un viaje.', 'Bernabé era mi primo.'], 'Con el tiempo Pablo dijo que le era útil.'),
  C(8, 'Silas', 'Compañero de Pablo', 'Hechos 16:25', ['Cantamos alabanzas en la cárcel a medianoche.', 'Un terremoto abrió las puertas.'], 'Acompañó a Pablo en su segundo viaje.'),
  C(8, 'Lidia', 'Vendedora de púrpura', 'Hechos 16:14', ['Vivía en Filipos.', 'Insistí en que los misioneros se quedaran en mi casa.'], 'Jehová le abrió el corazón para escuchar a Pablo.'),
  C(8, 'Timoteo', 'Joven compañero de Pablo', '2 Timoteo 1:5', ['Mi madre y mi abuela me enseñaron las Escrituras.', 'Pablo me llamaba su hijo amado.'], 'Pablo le escribió dos cartas.'),
  C(8, 'Priscila y Áquila', 'Matrimonio que hacía tiendas', 'Hechos 18:26', ['Trabajamos con Pablo haciendo tiendas.', 'Le explicamos con más exactitud el camino de Dios a un predicador elocuente.'], 'Arriesgaron su vida por Pablo.'),
  C(8, 'Apolos', 'Predicador elocuente', 'Hechos 18:24', ['Era de Alejandría y conocía bien las Escrituras.', 'Solo conocía el bautismo de Juan.'], 'Aceptó con humildad que lo corrigieran.'),
  C(8, 'Eutico', 'Joven que cayó de una ventana', 'Hechos 20:9', ['Me dormí durante un discurso largo de Pablo.', 'Me caí desde un tercer piso.'], 'Pablo lo resucitó.'),
  C(8, 'Lucas', 'El médico amado', 'Colosenses 4:14', ['Viajé con Pablo.', 'Escribí un Evangelio y el libro de Hechos.'], 'Investigó todo con cuidado antes de escribir.'),
]

const slug = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
// id estable (para el progreso) y posición en la historia (para la línea del tiempo).
export const CHARACTERS = LIST.map((ch, i) => ({ ...ch, id: slug(ch.n), order: i }))
